version: "1.0"
services:
  backend:
    build: ./
    image: backend
    container_name: backend
    restart: always
    network_mode: "host"
    ports:
      - 8282:8282
    # networks:
    #   - bicasnet
    volumes:
      - ./logs/:/Backend/logs/
